chars = {}
chars[0x00]=' ' --#define CHAR_SPACE             0x00
chars[0x01]='?' --#define CHAR_A_GRAVE           0x01
chars[0x02]='?' --#define CHAR_A_ACUTE           0x02
chars[0x03]='?' --#define CHAR_A_CIRCUMFLEX      0x03
chars[0x04]='ç' --#define CHAR_C_CEDILLA         0x04
chars[0x05]='è' --#define CHAR_E_GRAVE           0x05
chars[0x06]='é' --string.char(130) --#define CHAR_E_ACUTE           0x06 --é 
chars[0x07]='ê' --#define CHAR_E_CIRCUMFLEX      0x07
chars[0x08]='ë' --#define CHAR_E_DIAERESIS       0x08
chars[0x09]='i' --#define CHAR_I_GRAVE           0x09
chars[0x0A]='i' --//#define CHAR_I_ACUTE         0x0A // Is 0x5A instead
chars[0x0B]='î' --#define CHAR_I_CIRCUMFLEX      0x0B
chars[0x0C]='ï' --#define CHAR_I_DIAERESIS       0x0C
chars[0x0D]='?' --#define CHAR_O_GRAVE           0x0D
chars[0x0E]='?' --#define CHAR_O_ACUTE           0x0E
chars[0x0F]='?' --#define CHAR_O_CIRCUMFLEX      0x0F
chars[0x10]='?' --#define CHAR_OE                0x10
chars[0x11]='?' --#define CHAR_U_GRAVE           0x11    
chars[0x12]='?' --#define CHAR_U_ACUTE           0x12
chars[0x13]='?' --#define CHAR_U_CIRCUMFLEX      0x13
chars[0x14]='?' --#define CHAR_N_TILDE           0x14
chars[0x15]='?' --#define CHAR_ESZETT            0x15
chars[0x16]='a' --#define CHAR_a_GRAVE           0x16
chars[0x17]='?' --#define CHAR_a_ACUTE           0x17
chars[0x18]='?' --//#define CHAR_a_CIRCUMFLEX    0x18 // Is 0x68 instead
chars[0x19]='?' --#define CHAR_c_CEDILLA         0x19
chars[0x1A]='è' --#define CHAR_e_GRAVE           0x1A
chars[0x1B]='é' --string.char(130) --#define CHAR_e_ACUTE           0x1B //É
chars[0x1C]='ê' --#define CHAR_e_CIRCUMFLEX      0x1C
chars[0x1D]='?' --#define CHAR_e_DIAERESIS       0x1D
chars[0x1E]='?' --#define CHAR_i_GRAVE           0x1E
chars[0x1F]='?' --//#define CHAR_i_ACUTE         0x1F // Is 0x6F instead
chars[0x20]='î' --#define CHAR_i_CIRCUMFLEX      0x20
chars[0x21]='?' --#define CHAR_i_DIAERESIS       0x21
chars[0x22]='o' --#define CHAR_o_GRAVE           0x22
chars[0x23]='o' --#define CHAR_o_ACUTE           0x23
chars[0x24]='o' --#define CHAR_o_CIRCUMFLEX      0x24
chars[0x25]='eu' --#define CHAR_oe                0x25
chars[0x26]='u' --#define CHAR_u_GRAVE           0x26
chars[0x27]='u' --#define CHAR_u_ACUTE           0x27
chars[0x28]='u' --#define CHAR_u_CIRCUMFLEX      0x28
chars[0x29]='?' --#define CHAR_n_TILDE           0x29
chars[0x2A]='?' --#define CHAR_MASCULINE_ORDINAL 0x2A
chars[0x2B]='?' --#define CHAR_FEMININE_ORDINAL  0x2B
chars[0x2C]='?' --#define CHAR_SUPER_ER          0x2C
chars[0x2D]='&' --#define CHAR_AMPERSAND         0x2D
chars[0x2E]='+' --#define CHAR_PLUS              0x2E
chars[0x34]='?' --#define CHAR_LV                0x34
chars[0x35]='=' --#define CHAR_EQUALS            0x35
chars[0x36]=';' --#define CHAR_SEMICOLON         0x36
chars[0x51]='?' --#define CHAR_INV_QUESTION_MARK 0x51
chars[0x52]='?' --#define CHAR_INV_EXCL_MARK     0x52
chars[0x53]='Pokemon' --#define CHAR_PK                0x53
chars[0x54]='?' --#define CHAR_MN                0x54
chars[0x55]='Pokemon' --#define CHAR_PO                0x55
chars[0x56]='?' --#define CHAR_KE                0x56
chars[0x57]='block' --#define CHAR_BLOCK_1           0x57 // Each of these 3
chars[0x58]=' ' --#define CHAR_BLOCK_2           0x58 // chars contains 1/3
chars[0x59]=' ' --#define CHAR_BLOCK_3           0x59 // of the word BLOCK
chars[0x5A]='?' --#define CHAR_I_ACUTE           0x5A
chars[0x5B]='%' --#define CHAR_PERCENT           0x5B
chars[0x5C]='(' --#define CHAR_LEFT_PAREN        0x5C
chars[0x5D]=')' --#define CHAR_RIGHT_PAREN       0x5D
chars[0x68]='â' --#define CHAR_a_CIRCUMFLEX      0x68
chars[0x6F]='?' --#define CHAR_i_ACUTE           0x6F
chars[0x77]='?' --#define CHAR_GENDERLESS        0x77 // Empty space for lack of gender icon
chars[0x79]='?' --#define CHAR_UP_ARROW          0x79
chars[0x7A]='?' --#define CHAR_DOWN_ARROW        0x7A
chars[0x7B]='?' --#define CHAR_LEFT_ARROW        0x7B
chars[0x7C]='?' --#define CHAR_RIGHT_ARROW       0x7C
chars[0x84]='?' --#define CHAR_SUPER_E           0x84
chars[0x85]='<' --#define CHAR_LESS_THAN         0x85
chars[0x86]='>' --#define CHAR_GREATER_THAN      0x86
chars[0xA0]='?' --#define CHAR_SUPER_RE          0xA0
chars[0xA1]='0' --#define CHAR_0                 0xA1
chars[0xA2]='1' --#define CHAR_1                 0xA2
chars[0xA3]='2' --#define CHAR_2                 0xA3
chars[0xA4]='3' --#define CHAR_3                 0xA4
chars[0xA5]='4' --#define CHAR_4                 0xA5
chars[0xA6]='5' --#define CHAR_5                 0xA6
chars[0xA7]='6' --#define CHAR_6                 0xA7
chars[0xA8]='7' --#define CHAR_7                 0xA8
chars[0xA9]='8' --#define CHAR_8                 0xA9
chars[0xAA]='9' --#define CHAR_9                 0xAA
chars[0xAB]='!' --#define CHAR_EXCL_MARK         0xAB
chars[0xAC]='?' --#define CHAR_QUESTION_MARK     0xAC
chars[0xAD]='.' --#define CHAR_PERIOD            0xAD
chars[0xAE]='-' --#define CHAR_HYPHEN            0xAE
chars[0xAF]='...' --#define CHAR_BULLET            0xAF
chars[0xB0]='...' --#define CHAR_ELLIPSIS          0xB0
chars[0xB1]='"' --#define CHAR_DBL_QUOT_LEFT     0xB1
chars[0xB2]='"' --#define CHAR_DBL_QUOT_RIGHT    0xB2
chars[0xB3]="'" --#define CHAR_SGL_QUOT_LEFT     0xB3
chars[0xB4]="'" --#define CHAR_SGL_QUOT_RIGHT    0xB4
chars[0xB5]=lang[vl].male --#define CHAR_MALE              0xB5
chars[0xB6]=lang[vl].female --#define CHAR_FEMALE            0xB6
chars[0xB7]=lang[vl].credits --#define CHAR_CURRENCY          0xB7
chars[0xB8]=',' --#define CHAR_COMMA             0xB8
chars[0xB9]='*' --#define CHAR_MULT_SIGN         0xB9
chars[0xBA]='/' --#define CHAR_SLASH             0xBA
chars[0xBB]='A' --#define CHAR_A                 0xBB
chars[0xBC]='B' --#define CHAR_B                 0xBC
chars[0xBD]='C' --#define CHAR_C                 0xBD
chars[0xBE]='D' --#define CHAR_D                 0xBE
chars[0xBF]='E' --#define CHAR_E                 0xBF
chars[0xC0]='F' --#define CHAR_F                 0xC0
chars[0xC1]='G' --#define CHAR_G                 0xC1
chars[0xC2]='H' --#define CHAR_H                 0xC2
chars[0xC3]='I' --#define CHAR_I                 0xC3
chars[0xC4]='J' --#define CHAR_J                 0xC4
chars[0xC5]='K' --#define CHAR_K                 0xC5
chars[0xC6]='L' --#define CHAR_L                 0xC6
chars[0xC7]='M' --#define CHAR_M                 0xC7
chars[0xC8]='N' --#define CHAR_N                 0xC8
chars[0xC9]='O' --#define CHAR_O                 0xC9
chars[0xCA]='P' --#define CHAR_P                 0xCA
chars[0xCB]='Q' --#define CHAR_Q                 0xCB
chars[0xCC]='R' --#define CHAR_R                 0xCC
chars[0xCD]='S' --#define CHAR_S                 0xCD
chars[0xCE]='T' --#define CHAR_T                 0xCE
chars[0xCF]='U' --#define CHAR_U                 0xCF
chars[0xD0]='V' --#define CHAR_V                 0xD0
chars[0xD1]='W' --#define CHAR_W                 0xD1
chars[0xD2]='X' --#define CHAR_X                 0xD2
chars[0xD3]='Y' --#define CHAR_Y                 0xD3
chars[0xD4]='Z' --#define CHAR_Z                 0xD4
chars[0xD5]='a' --#define CHAR_a                 0xD5
chars[0xD6]='b' --#define CHAR_b                 0xD6
chars[0xD7]='c' --#define CHAR_c                 0xD7
chars[0xD8]='d' --#define CHAR_d                 0xD8
chars[0xD9]='e' --#define CHAR_e                 0xD9
chars[0xDA]='f' --#define CHAR_f                 0xDA
chars[0xDB]='g' --#define CHAR_g                 0xDB
chars[0xDC]='h' --#define CHAR_h                 0xDC
chars[0xDD]='i' --#define CHAR_i                 0xDD
chars[0xDE]='j' --#define CHAR_j                 0xDE
chars[0xDF]='k' --#define CHAR_k                 0xDF
chars[0xE0]='l' --#define CHAR_l                 0xE0
chars[0xE1]='m' --#define CHAR_m                 0xE1
chars[0xE2]='n' --#define CHAR_n                 0xE2
chars[0xE3]='o' --#define CHAR_o                 0xE3
chars[0xE4]='p' --#define CHAR_p                 0xE4
chars[0xE5]='q' --#define CHAR_q                 0xE5
chars[0xE6]='r' --#define CHAR_r                 0xE6
chars[0xE7]='s' --#define CHAR_s                 0xE7
chars[0xE8]='t' --#define CHAR_t                 0xE8
chars[0xE9]='u' --#define CHAR_u                 0xE9
chars[0xEA]='v' --#define CHAR_v                 0xEA
chars[0xEB]='w' --#define CHAR_w                 0xEB
chars[0xEC]='x' --#define CHAR_x                 0xEC
chars[0xED]='y' --#define CHAR_y                 0xED
chars[0xEE]='z' --#define CHAR_z                 0xEE
chars[0xEF]='?' --#define CHAR_BLACK_TRIANGLE    0xEF
chars[0xF0]=':' --#define CHAR_COLON             0xF0
chars[0xF1]='?' --#define CHAR_A_DIAERESIS       0xF1
chars[0xF2]='?' --#define CHAR_O_DIAERESIS       0xF2
chars[0xF3]='?' --#define CHAR_U_DIAERESIS       0xF3
chars[0xF4]='?' --#define CHAR_a_DIAERESIS       0xF4
chars[0xF5]='?' --#define CHAR_o_DIAERESIS       0xF5
chars[0xF6]='?' --#define CHAR_u_DIAERESIS       0xF6
chars[0xF7]='?' --#define CHAR_DYNAMIC           0xF7
chars[0xF8]='?' --#define CHAR_KEYPAD_ICON       0xF8
chars[0xF9]='?' --#define CHAR_EXTRA_SYMBOL      0xF9
chars[0xFA]='{' --#define CHAR_PROMPT_SCROLL     0xFA // waits for button press and scrolls dialog }
chars[0xFB]='{' --#define CHAR_PROMPT_CLEAR      0xFB // waits for button press and clears dialog }}
chars[0xFC]=' ' --#define EXT_CTRL_CODE_BEGIN    0xFC // extended control code
chars[0xFD]='?' --#define PLACEHOLDER_BEGIN      0xFD // string placeholder
chars[0xFE]=' ' --#define CHAR_NEWLINE           0xFE
chars[0xFF]=' ' --#define EOS                    0xFF // end of string

