function voice_battlers_duo(lg, ally_pokemon, enemy_pokemon)
	local a = ally_pokemon
	local e = enemy_pokemon
	
	local e_gender = lang[lg][get_gender(e["personality"],e.specie+1)]
	
	if lg == "fr" then
		return a.name .. " niveau " .. a.level .. " santé " .. a.hp .. " sur " .. a.maxHP .. ", " .. e.name .. " " .. e_gender .. " enemi niveau " .. e.level .. " santé " .. e.percent_hp .. " pourcent"
	end
	if lg == "en" then
		return a.name .. " level " .. a.level .. " hit points " .. a.hp .. " over " .. a.maxHP .. ", enemy " .. e_gender .. " " .. e.name .. " level " .. e.level.. " hit points " .. e.percent_hp .. " percent"
	end
end

function voice_battlers_multi(lg, battlers)
	local a1 = battlers[0]
	local a2 = battlers[2]
	local e1 = battlers[1]
	local e2 = battlers[3]
	
	local e1_gender = lang[lg][get_gender(e1["personality"],e1.specie+1)]
	local e2_gender = lang[lg][get_gender(e2["personality"],e2.specie+1)]
	
	if lg == "fr" then
		return "Vos pokemon . " ..
			a1.name .. " niveau " .. a1.level .. " santé " .. a1.hp .. " sur " .. a1.maxHP .. ", " ..
			a2.name .. " niveau " .. a2.level .. " santé " .. a2.hp .. " sur " .. a2.maxHP .. ", " ..			
			". pokemon enemis . " ..
			e1.name .. " " .. e1_gender .. " niveau " .. e1.level .. " santé " .. e1.percent_hp .. " pourcent" ..
			e2.name .. " " .. e2_gender .. " niveau " .. e2.level .. " santé " .. e2.percent_hp .. " pourcent"			
	end
	if lg == "en" then
		return "Your pokemons . " ..
			a1.name .. " level " .. a1.level .. " hit points " .. a1.hp .. " over " .. a1.maxHP .. ", " ..
			a2.name .. " level " .. a2.level .. " hit points " .. a2.hp .. " over " .. a2.maxHP .. ", " ..
			"enemy pokemons . " ..
			e1_gender .. " " .. e1.name .. " level " .. e1.level.. " hit points " .. e1.percent_hp .. " percent " ..
			e2_gender .. " " .. e2.name .. " level " .. e2.level.. " hit points " .. e2.percent_hp .. " percent " 
	end
end

--[[
function voice_party_pokemon_stats(lg,id,name)
	local pokemon = Program.getPokemonData({player = 1,slot = id})
	
	local gender = lang[lg][get_gender(pokemon["personality"],pokemon["pokemonID"] + 1)]

	if lg == "fr" then
		return lang.fr.name[pokemon["pokemonID"] + 1] .. " " .. gender .. " niveau " .. pokemon["level"] .. " santé " .. pokemon["curHP"] .. " sur " .. pokemon["maxHP"] .. " "

	end
	if lg == "en" then

		return gender .. " " .. lang.en.name[pokemon["pokemonID"] + 1] .. " level " .. pokemon["level"] .. " hit points " .. pokemon["curHP"] .. " over " .. pokemon["maxHP"] .. " "
	end
end
]]

lang = {}
lang.fr = {}
lang.fr = {
	new_game = "Nouvelle Partie",
	options = "Options",
	continue = "Continuer",
	mystery_gift = "Cadeau mystère",
	mystery_events = "événement mystère",
	
	window = "window ",
	read_windows = "Lire les fenêtres",
	credits = "crédits",
	zone = "zone ",
	event = "évènement",
	north_event = "évènement face nord",
	south_event = "évènement face sud",
	east_event = "évènement face est",
	west_event = "évènement face ouest",
	hidden_event = "évènement caché",
	secret_base_event = "évènement base secrète",

	log_menu = "Menu journal",
	poi_menu = "Menu points d'intérêt",
	entity_mode = "Mode entité",
	passage_mode = "Mode passage",
	event_mode = "Mode évènement",
	connection_mode = "Mode connexion",
	distance = " distance ",

	game_title = "Pokémon, version émeraude, appuyez sur start",
	change_time_ok = "Est-ce la bonne heure ?",

	fight = "Attaque",
	bag = "Sac",
	pokemon = "Pokémon",
	run = "Fuite",

	action_menu = "Que doit faire ",
	move_menu = "Menu attaque",
	game_menu = "Menu du jeu ...",
	gender_menu = "Menu du genre ...",
	yes_no_menu = "Menu oui non ...",
	pause_menu = "Menu de pause ...",
	shop_menu = "Menu magasin ...",	
	pc_menu = "Menu PC ...",
	
	game_keyboard = "Menu clavier du jeu", 

	new_turn = new_turn_f,

	youareon = "Vous êtes sur ",

	pokemon_choose = "choisir un pokémon",
	leave = "Sortir",
	change = "changer ",
	_for = "pour ",
	slot = "emplacement ",
	
	items_pocket = "Poche objets",
	balls_pocket = "Poche pockéballs",
	thhm_pocket = "Poche C,T & C,S",
	berries_pocket = "Poche baies",
	keyitems_pocket = "Poche objets rares",
	
	upper_case = "mode majuscule",
	lower_case = "mode minuscule",
	other = "mode autres caractères",
	backspace = "retour",
	
	entry = "entrée ",
	targeted = " ciblé",
	
	female = "femelle",
	male = "male",
	genderless = "",
	
	selected = " sélectionné",
	connection = "connexion",
}

lang.fr.connections = {
	SOUTH = "connexion sud",
	NORTH = "connexion nord",
	WEST = "connexion ouest",
	EAST = "connexion est",
	DIVE = "connexion plongée",
	EMERGE = "connexion surface",
}

lang.fr.name = {
	"---",
	"Bulbizarre ",
	"Herbizarre ",
	"Florizarre ",
	"Salamèche ",
	"Reptincel ",
	"Dracaufeu ",
	"Carapuce ",
	"Carabaffe ",
	"Tortank ",
	"Chenipan ",
	"Chrysacier ",
	"Papilusion ",
	"Aspicot ",
	"Coconfort ",
	"Dardargnan ",
	"Roucool ",
	"Roucoups ",
	"Roucarnage ",
	"Rattata ",
	"Rattatac ",
	"Piafabec ",
	"Rapasdepic ",
	"Abo ",
	"Arbok ",
	"Pikachu ",
	"Raichu ",
	"Sabelette ",
	"Sablaireau ",
	"Nidoran F",
	"Nidorina ",
	"Nidoqueen ",
	"Nidoran M",
	"Nidorino ",
	"Nidoking ",
	"Mélofée ",
	"Mélodelfe ",
	"Goupix ",
	"Feunard ",
	"Rondoudou ",
	"Grodoudou ",
	"Nosferapti ",
	"Nosferalto ",
	"Mystherbe ",
	"Ortide ",
	"Rafflesia ",
	"Paras ",
	"Parasect ",
	"Mimitoss ",
	"Aéromite ",
	"Taupiqueur ",
	"Triopikeur ",
	"Miaouss ",
	"Persian ",
	"Psykokwak ",
	"Akwakwak ",
	"Férosinge ",
	"Colossinge ",
	"Caninos ",
	"Arcanin ",
	"Ptitard ",
	"Têtarte ",
	"Tartard ",
	"Abra ",
	"Kadabra ",
	"Alakazam ",
	"Machoc ",
	"Machopeur ",
	"Mackogneur ",
	"Chétiflor ",
	"Boustiflor ",
	"Empiflor ",
	"Tentacool ",
	"Tentacruel ",
	"Racaillou ",
	"Gravalanch ",
	"Grolem ",
	"Ponyta ",
	"Galopa ",
	"Ramoloss ",
	"Flagadoss ",
	"Magnéti ",
	"Magnéton ",
	"Canarticho ",
	"Doduo ",
	"Dodrio ",
	"Otaria ",
	"Lamantine ",
	"Tadmorv ",
	"Grotadmorv ",
	"Kokiyas ",
	"Crustabri ",
	"Fantominus ",
	"Spectrum ",
	"Ectoplasma ",
	"Onix ",
	"Soporifik ",
	"Hypnomade ",
	"Krabby ",
	"Krabboss ",
	"Voltorbe ",
	"Électrode ",
	"Noeunoeuf ",
	"Noadkoko ",
	"Osselait ",
	"Ossatueur ",
	"Kicklee ",
	"Tygnon ",
	"Excelangue ",
	"Smogo ",
	"Smogogo ",
	"Rhinocorne ",
	"Rhinoféros ",
	"Leveinard ",
	"Saquedeneu ",
	"Kangourex ",
	"Hypotrempe ",
	"Hypocéan ",
	"Poissirène ",
	"Poissoroy ",
	"Stari ",
	"Staross ",
	"M. Mime ",
	"Insécateur ",
	"Lippoutou ",
	"Élektek ",
	"Magmar ",
	"Scarabrute ",
	"Tauros ",
	"Magicarpe ",
	"Léviator ",
	"Lokhlass ",
	"Métamorph ",
	"Évoli ",
	"Aquali ",
	"Voltali ",
	"Pyroli ",
	"Porygon ",
	"Amonita ",
	"Amonistar ",
	"Kabuto ",
	"Kabutops ",
	"Ptéra ",
	"Ronflex ",
	"Artikodin ",
	"Électhor ",
	"Sulfura ",
	"Minidraco ",
	"Draco ",
	"Dracolosse ",
	"Mewtwo ",
	"Mew ",
	"Germignon ",
	"Macronium ",
	"Méganium ",
	"Héricendre ",
	"Feurisson ",
	"Typhlosion ",
	"Kaiminus ",
	"Crocrodil ",
	"Aligatueur ",
	"Fouinette ",
	"Fouinar ",
	"Hoothoot ",
	"Noarfang ",
	"Coxy ",
	"Coxyclaque ",
	"Mimigal ",
	"Migalos ",
	"Nostenfer ",
	"Loupio ",
	"Lanturn ",
	"Pichu ",
	"Mélo ",
	"Toudoudou ",
	"Togepi ",
	"Togetic ",
	"Natu ",
	"Xatu ",
	"Wattouat ",
	"Lainergie ",
	"Pharamp ",
	"Joliflor ",
	"Marill ",
	"Azumarill ",
	"Simularbre ",
	"Tarpaud ",
	"Granivol ",
	"Floravol ",
	"Cotovol ",
	"Capumain ",
	"Tournegrin ",
	"Héliatronc ",
	"Yanma ",
	"Axoloto ",
	"Maraiste ",
	"Mentali ",
	"Noctali ",
	"Cornèbre ",
	"Roigada ",
	"Feuforêve ",
	"Zarbi ",
	"Qulbutoké ",
	"Girafarig ",
	"Pomdepik ",
	"Foretress ",
	"Insolourdo ",
	"Scorplane ",
	"Steelix ",
	"Snubbull ",
	"Granbull ",
	"Qwilfish ",
	"Cizayox ",
	"Caratroc ",
	"Scarhino ",
	"Farfuret ",
	"Teddiursa ",
	"Ursaring ",
	"Limagma ",
	"Volcaropod ",
	"Marcacrin ",
	"Cochignon ",
	"Corayon ",
	"Rémoraid ",
	"Octillery ",
	"Cadoizo ",
	"Démanta ",
	"Airmure ",
	"Malosse ",
	"Démolosse ",
	"Hyporoi ",
	"Phanpy ",
	"Donphan ",
	"Porygon2 ",
	"Cerfrousse ",
	"Queulorior ",
	"Debugant ",
	"Kapoera ",
	"Lippouti ",
	"Élekid ",
	"Magby ",
	"Écrémeuh ",
	"Leuphorie ",
	"Raikou ",
	"Entei ",
	"Suicune ",
	"Embrylex ",
	"Ymphect ",
	"Tyranocif ",
	"Lugia ",
	"Ho-Oh ",
	"Celebi ",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Aucun",
	"Arcko ",
	"Massko ",
	"Jungko ",
	"Poussifeu ",
	"Galifeu ",
	"Braségali ",
	"Gobou ",
	"Flobio ",
	"Laggron ",
	"Medhyèna ",
	"Grahyèna ",
	"Zigzaton ",
	"Linéon ",
	"Chenipotte ",
	"Armulys ",
	"Charmillon ",
	"Blindalys ",
	"Papinox ",
	"Nénupiot ",
	"Lombre ",
	"Ludicolo ",
	"Grainipiot ",
	"Pifeuil ",
	"Tengalice ",
	"Ningale ",
	"Ninjask ",
	"Munja ",
	"Nirondelle ",
	"Hélédelle ",
	"Balignon ",
	"Chapignon ",
	"Spinda ",
	"Goélise ",
	"Bekipan ",
	"Arakdo ",
	"Maskadra ",
	"Wailmer ",
	"Wailord ",
	"Skitty ",
	"Delcatty ",
	"Kecleon ",
	"Balbuto ",
	"Kaorine ",
	"Tarinor ",
	"Chartor ",
	"Ténéfix ",
	"Barloche ",
	"Barbicha ",
	"Lovdisc ",
	"Écrapince ",
	"Colhomard ",
	"Barpau ",
	"Milobellus ",
	"Carvanha ",
	"Sharpedo ",
	"Kraknoix ",
	"Vibraninf ",
	"Libégon ",
	"Makuhita ",
	"Hariyama ",
	"Dynavolt ",
	"Élecsprint ",
	"Chamallot ",
	"Camérupt ",
	"Obalie ",
	"Phogleur ",
	"Kaimorse ",
	"Cacnea ",
	"Cacturne ",
	"Stalgamin ",
	"Oniglali ",
	"Séléroc ",
	"Solaroc ",
	"Azurill ",
	"Spoink ",
	"Groret ",
	"Posipi ",
	"Négapi ",
	"Mysdibule ",
	"Méditikka ",
	"Charmina ",
	"Tylton ",
	"Altaria ",
	"Okéoké ",
	"Skelénox ",
	"Téraclope ",
	"Rosélia ",
	"Parecool ",
	"Vigoroth ",
	"Monaflèmit ",
	"Gloupti ",
	"Avaltout ",
	"Tropius ",
	"Chuchmur ",
	"Ramboum ",
	"Brouhabam ",
	"Coquiperl ",
	"Serpang ",
	"Rosabyss ",
	"Absol ",
	"Polichombr ",
	"Branette ",
	"Séviper ",
	"Mangriff ",
	"Relicanth ",
	"Galekid ",
	"Galegon ",
	"Galeking ",
	"Morphéo ",
	"Muciole ",
	"Lumivole ",
	"Lilia ",
	"Vacilys ",
	"Anorith ",
	"Armaldo ",
	"Tarsal ",
	"Kirlia ",
	"Gardevoir ",
	"Draby ",
	"Drackhaus ",
	"Drattak ",
	"Terhal ",
	"Métang ",
	"Métalosse ",
	"Regirock ",
	"Regice ",
	"Registeel ",
	"Kyogre ",
	"Groudon ",
	"Rayquaza ",
	"Latias ",
	"Latios ",
	"Jirachi ",
	"Deoxys ",
	"Éoko ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
	"Zarbi ",
}
lang.fr.move = {
	"-",
	"Ecras'Face",
	"Poing-Karate",
	"Torgnoles",
	"Poing Comete",
	"Ultimapoing",
	"Jackpot",
	"Poing De Feu",
	"Poinglace",
	"Poing-Eclair",
	"Griffe",
	"Force Poigne",
	"Guillotine",
	"Coupe-Vent",
	"Danse-Lames",
	"Coupe",
	"Tornade",
	"Cru-Aile",
	"Cyclone",
	"Vol",
	"Etreinte",
	"Souplesse",
	"Fouet Lianes",
	"Ecrasement",
	"Double Pied",
	"Ultimawashi",
	"Pied Saute",
	"Mawashi Geri",
	"Jet De Sable",
	"Coup D'Boule",
	"Koud'Korne",
	"Furie",
	"Empal'Korne",
	"Charge",
	"Plaquage",
	"Ligotage",
	"Belier",
	"Mania",
	"Damocles",
	"Mimi-Queue",
	"Dard-Venin",
	"Double-Dard",
	"Dard-Nuee",
	"Groz'Yeux",
	"Morsure",
	"Rugissement",
	"Hurlement",
	"Berceuse",
	"Ultrason",
	"Sonicboom",
	"Entrave",
	"Acide",
	"Flammeche",
	"Lance-Flamme",
	"Brume",
	"Pistolet A O",
	"Hydrocanon",
	"Surf",
	"Laser Glace",
	"Blizzard",
	"Rafale Psy",
	"Bulles D'O",
	"Onde Boreale",
	"Ultralaser",
	"Picpic",
	"Bec Vrille",
	"Sacrifice",
	"Balayage",
	"Riposte",
	"Frappe Atlas",
	"Force",
	"Vol-Vie",
	"Mega-Sangsue",
	"Vampigraine",
	"Croissance",
	"Tranch'Herbe",
	"Lance-Soleil",
	"Poudre Toxik",
	"Para-Spore",
	"Poudre Dodo",
	"Danse-Fleur",
	"Secretion",
	"Draco-Rage",
	"Danseflamme",
	"Eclair",
	"Tonnerre",
	"Cage-Eclair",
	"Fatal-Foudre",
	"Jet-Pierres",
	"Seisme",
	"Abime",
	"Tunnel",
	"Toxik",
	"Choc Mental",
	"Psyko",
	"Hypnose",
	"Yoga",
	"Hate",
	"Vive-Attaque",
	"Frenesie",
	"Teleport",
	"Tenebres",
	"Copie",
	"Grincement",
	"Reflet",
	"Soin",
	"Armure",
	"Lilliput",
	"Brouillard",
	"Onde Folie",
	"Repli",
	"Boul'Armure",
	"Bouclier",
	"Mur Lumiere",
	"Buee Noire",
	"Protection",
	"Puissance",
	"Patience",
	"Metronome",
	"Mimique",
	"Destruction",
	"Bomb'Oeuf",
	"Lechouille",
	"Puredpois",
	"Detritus",
	"Massd'Os",
	"Deflagration",
	"Cascade",
	"Claquoir",
	"Meteores",
	"Coud'Krane",
	"Picanon",
	"Constriction",
	"Amnesie",
	"Telekinesie",
	"E-Coque",
	"Pied Voltige",
	"Intimidation",
	"Devoreve",
	"Gaz Toxik",
	"Pilonnage",
	"Vampirisme",
	"Grobisou",
	"Pique",
	"Morphing",
	"Ecume",
	"Uppercut",
	"Spore",
	"Flash",
	"Vague Psy",
	"Trempette",
	"Acidarmure",
	"Pince-Masse",
	"Explosion",
	"Combo-Griffe",
	"Osmerang",
	"Repos",
	"Eboulement",
	"Croc De Mort",
	"Affutage",
	"Adaptation",
	"Triplattaque",
	"Croc Fatal",
	"Tranche",
	"Clonage",
	"Lutte",
	"Gribouille",
	"Triple Pied",
	"Larcin",
	"Toile",
	"Lire-Esprit",
	"Cauchemar",
	"Roue De Feu",
	"Ronflement",
	"Malediction",
	"Fleau",
	"Conversion 2",
	"Aeroblast",
	"Spore Coton",
	"Contre",
	"Depit",
	"Poudreuse",
	"Abri",
	"Mach Punch",
	"Grimace",
	"Feinte",
	"Doux Baiser",
	"Cognobidon",
	"Bomb-Beurk",
	"Coud'Boue",
	"Octazooka",
	"Picots",
	"Elecanon",
	"Clairvoyance",
	"Prlvt Destin",
	"Requiem",
	"Vent Glace",
	"Detection",
	"Charge-Os",
	"Verrouillage",
	"Colere",
	"Tempetesable",
	"Giga-Sangsue",
	"Tenacite",
	"Charme",
	"Roulade",
	"Faux-Chage",
	"Vantardise",
	"Lait A Boire",
	"Etincelle",
	"Taillade",
	"Aile D'Acier",
	"Regard Noir",
	"Attraction",
	"Blabla Dodo",
	"Glas De Soin",
	"Retour",
	"Cadeau",
	"Frustration",
	"Rune Protect",
	"Balance",
	"Feu Sacre",
	"Ampleur",
	"Dynamopoing",
	"Megacorne",
	"Dracosouffle",
	"Relais",
	"Encore",
	"Poursuite",
	"Tour Rapide",
	"Doux Parfum",
	"Queue De Fer",
	"Griffe Acier",
	"Corps Perdu",
	"Aurore",
	"Synthese",
	"Rayon Lune",
	"Puis. Cachee",
	"Coup-Croix",
	"Ouragan",
	"Danse Pluie",
	"Zenith",
	"Machouille",
	"Voile Miroir",
	"Boost",
	"Vit.Extreme",
	"Pouv.Antique",
	"Ball'Ombre",
	"Prescience",
	"Eclate-Roc",
	"Siphon",
	"Baston",
	"Bluff",
	"Brouhaha",
	"Stockage",
	"Relache",
	"Avale",
	"Canicule",
	"Grele",
	"Tourmente",
	"Flatterie",
	"Feu Follet",
	"Souvenir",
	"Facade",
	"Mitra-Poing",
	"Stimulant",
	"Par Ici",
	"Force-Nature",
	"Chargeur",
	"Provoc",
	"Coup D'Main",
	"Tourmagik",
	"Imitation",
	"Voeu",
	"Assistance",
	"Racines",
	"Surpuissance",
	"Reflet Magik",
	"Recyclage",
	"Vendetta",
	"Casse-Brique",
	"Baillement",
	"Sabotage",
	"Effort",
	"Eruption",
	"Echange",
	"Possessif",
	"Regeneration",
	"Rancune",
	"Saisie",
	"Force Cachee",
	"Plongee",
	"Cogne",
	"Camouflage",
	"Lumiqueue",
	"Lumi-Eclat",
	"Ball'Brume",
	"Danse-Plume",
	"Danse-Folle",
	"Pied Bruleur",
	"Lance-Boue",
	"Ball'Glace",
	"Poing Dard",
	"Paresse",
	"Megaphone",
	"Crochetvenin",
	"Eclategriffe",
	"Rafale Feu",
	"Hydroblast",
	"Poing Meteor",
	"Etonnement",
	"Ball'Meteo",
	"Aromatherapi",
	"Croco Larme",
	"Tranch'Air",
	"Surchauffe",
	"Flair",
	"Tomberoche",
	"Vent Argente",
	"Strido-Son",
	"Siffl'Herbe",
	"Chatouille",
	"Force Cosmik",
	"Gicledo",
	"Rayon Signal",
	"Poing Ombre",
	"Extrasenseur",
	"Stratopercut",
	"Tourbi-Sable",
	"Glaciation",
	"Ocroupi",
	"Balle Graine",
	"Aeropique",
	"Stalagtite",
	"Mur De Fer",
	"Barrage",
	"Grondement",
	"Dracogriffe",
	"Vege-Attak",
	"Gonflette",
	"Rebond",
	"Tir De Boue",
	"Queue-Poison",
	"Implore",
	"Electacle",
	"Feuillemagik",
	"Tourniquet",
	"Plenitude",
	"Lame-Feuille",
	"Danse Draco",
	"Boule Roc",
	"Onde De Choc",
	"Vibraqua",
	"Carnareket",
	"Psycho Boost",
	"Atterrissage",
	"Gravité",
	"Oeil Miracle",
	"Réveil Forcé",
	"Marto-Poing",
	"Gyroballe",
	"Voeu Soin",
	"Saumure",
	"Don Naturel",
	"Ruse",
	"Picore",
	"Vent Arrière",
	"Acupression",
	"Fulmifer",
	"Demi-Tour",
	"Close Combat",
	"Représailles",
	"Assurance",
	"Embargo",
	"Dégommage",
	"Échange Psy",
	"Atout",
	"Anti-Soin",
	"Essorage",
	"Astuce Force",
	"Suc Digestif",
	"Air Veinard",
	"Moi d'Abord",
	"Photocopie",
	"Permuforce",
	"Permugarde",
	"Punition",
	"Dernierecours",
	"Soucigraine",
	"Coup Bas",
	"Pics Toxik",
	"Permucoeur",
	"Anneau Hydro",
	"Vol Magnétik",
	"Boutefeu",
	"Forte-Paume",
	"Aurasphère",
	"Poliroche",
	"Direct Toxik",
	"Vibrobscur",
	"Tranche-Nuit",
	"Hydro-Queue",
	"Canon Graine",
	"Lame d'Air",
	"Plaie Croix",
	"Bourdon",
	"Draco-Choc",
	"Draco-Charge",
	"Rayon Gemme",
	"Vampi-Poing",
	"Onde Vide",
	"Exploforce",
	"Éco-Sphère",
	"Rapace",
	"Telluriforce",
	"Passe-Passe",
	"Giga Impact",
	"Machination",
	"Pisto-Poing",
	"Avalanche",
	"Éclats Glace",
	"Griffe Ombre",
	"Crocs Éclair",
	"Crocs Givre",
	"Crocs Feu",
	"Ombre Portée",
	"Boue-Bombe",
	"Coupe Psycho",
	"Psykoud'Boul",
	"Miroi-Tir",
	"Luminocanon",
	"Escalade",
	"Anti-Brume",
	"Distorsion",
	"Draco-Météore",
	"Coup d'Jus",
	"Ébullilave",
	"Tempête Verte",
	"Mégafouet",
	"Roc-Boulet",
	"Poison Croix",
	"Détricanon",
	"Tête de Fer",
	"Bombe Aimant",
	"Lame de Roc",
	"Séduction",
	"Piège de Roc",
	"Noeud Herbe",
	"Babil",
	"Jugement",
	"Piqûre",
	"Rayon Chargé",
	"Martobois",
	"Aqua-Jet",
	"Appel Attaque",
	"Appel Défense",
	"Appel Soins",
	"Fracass'Tête",
	"Coup Double",
	"Hurle-Temps",
	"Spatio-Rift",
	"Danse Lune",
	"Presse",
	"Vortex Magma",
	"Trou Noir",
	"Fulmigraine",
	"Vent Mauvais",
	"Revenant",
	"Aiguisage",
	"Garde Large",
	"Partage Garde",
	"Partage Force",
	"Zone Étrange",
	"Choc Psy",
	"Choc Venin",
	"Allègement",
	"Poudre Fureur",
	"Lévikinésie",
	"Zone Magique",
	"Anti-Air",
	"Yama Arashi",
	"Rebondifeu",
	"Cradovague",
	"Papillodanse",
	"Tacle Lourd",
	"Synchropeine",
	"Boule Élek",
	"Détrempage",
	"Nitrocharge",
	"Enroulement",
	"Balayette",
	"Bombe Acide",
	"Tricherie",
	"Rayon Simple",
	"Ten-Danse",
	"Après Vous",
	"Chant Canon",
	"Echo",
	"Attrition",
	"Bain de Smog",
	"Force Ajoutée",
	"Prévention",
	"Interversion",
	"Ébullition",
	"Exuviation",
	"Vibra Soin",
	"Châtiment",
	"Chute Libre",
	"Chgt Vitesse",
	"Projection",
	"Calcination",
	"À la Queue",
	"Acrobatie",
	"Copie-Type",
	"Vengeance",
	"Tout ou Rien",
	"Passe-Cadeau",
	"Feu d'Enfer",
	"Aire d'Eau",
	"Aire de Feu",
	"Aire d'Herbe",
	"Change Éclair",
	"Survinsecte",
	"Piétisol",
	"Souffle Glacé",
	"Draco-Queue",
	"Rengorgement",
	"Toile Élek",
	"Éclair Fou",
	"Tunnelier",
	"Double Baffe",
	"Crève-Coeur",
	"Encornebois",
	"Lame Sainte",
	"Coqui-Lame",
	"Tacle Feu",
	"Phytomixeur",
	"Bulldoboule",
	"Cotogarde",
	"Explonuit",
	"Frappe Psy",
	"Plumo-Queue",
	"Vent Violent",
	"Peignée",
	"Lancécrou",
	"Incendie",
	"Techno-Buster",
	"Chant Antique",
	"Lame Ointe",
	"Ère Glaciaire",
	"Charge Foudre",
	"Flamme Bleue",
	"Danse du Feu",
	"Éclair Gelé",
	"Feu Glacé",
	"Aboiement",
	"Chute Glace",
	"Coup Victoire",
	"Flamme Croix",
	"Éclair Croix",
	"Flying Press",
	"Tatamigaeshi",
	"Éructation",
	"Fertilisation",
	"Toile Gluante",
	"Dard Mortel",
	"Hantise",
	"Halloween",
	"Râle Mâle",
	"DélugePlasmik",
	"Parabocharge",
	"MaléfiSylvain",
	"TempêteFloral",
	"Lyophilisatn",
	"VoixEnjôleuse",
	"Dernier Mot",
	"Renversement",
	"Vampibaiser",
	"Vigilance",
	"Garde Florale",
	"Champ Herbu",
	"Champ Brumeux",
	"Électrisation",
	"Câlinerie",
	"Vent Féérique",
	"Pouv. Lunaire",
	"Bang Sonique",
	"VerrouEnchant",
	"BouclierRoyal",
	"Camaraderie",
	"Confidence",
	"Orage Adamant",
	"Jet de Vapeur",
	"TrouDimens.",
	"Sheauriken",
	"Feu Ensorcelé",
	"Pico-Défense",
	"Brume Capit.",
	"OndesÉtranges",
	"Piège Venin",
	"Nuée Poudre",
	"Géo-Contrôle",
	"MagnéContrôle",
	"Étrennes",
	"Champ Élect",
	"Éclat Magique",
	"Célébration",
	"Mains Jointes",
	"RegardTouchan",
	"FrotteFrimous",
	"Retenue",
	"Harcèlement",
	"Poing Boost",
	"Mort'Ailes",
	"Myria-Flèches",
	"Myria-Vagues",
	"ForceChtonien",
	"Lumière Néant",
	"Onde Origine",
	"LamePangéenne",
	"DracoAcension",
	"Furie Dimens.",
	"Amass'Sable",
	"Escarmouche",
	"Blockhaus",
	"Tisse Ombre",
	"Dark Lariat",
	"Aria d'Écume",
	"Marteau Glace",
	"Soin Floral",
	"CavaleriLourd",
	"Vole-Force",
	"Lame Solaire",
	"Feuillage",
	"Projecteur",
	"Fil Toxique",
	"Affilage",
	"Engrenage",
	"Exécu-Son",
	"Boule Pollen",
	"Ancrage",
	"Champ Psy",
	"Furie-Bond",
	"Fouet de Feu",
	"Arrogance",
	"Flamme Ultime",
	"Permuvitesse",
	"Estocorne",
	"Purification",
	"Danse Éveil",
	"SanctionSupr.",
	"BotteSucrette",
	"Sommation",
	"Bec-Canon",
	"Vibrécaille",
	"Draco-Marteau",
	"Centrifugifle",
	"Voile Aurore",
	"Carapiège",
	"Canon Floral",
	"Psycho-Croc",
	"Trépignement",
	"Os Ombre",
	"Vif Roc",
	"Aqua-Brèche",
	"Laser Prisme",
	"Clepto-Mânes",
	"Choc Météore",
	"RayonSpectral",
	"LarmeÀl'Oeil",
	"Électrikipik",
	"Ire de Nature",
	"CoupVariaType",
	"CabocheKaboum",
	"Plasma Punch",
	"Photo-Geyser",
	"Pika-Sprint",
	"Pika-Splash",
	"Pika-Piqué",
	"Pika-Fracas",
	"Évo-Thalasso",
	"Évo-Dynamo",
	"Évo-Flambo",
	"Évo-Psycho",
	"Évo-Ténébro",
	"Évo-Écolo",
	"Évo-Congélo",
	"Évo-Fabulo",
	"Évo-Chardasso",
	"Écroud'Poing",
	"Canon Dynamax",
	"Tir Précision",
	"Croque Fort",
	"Garde-à-Joues",
	"UltimeBastion",
	"Goudronnage",
	"PoudreMagique",
	"Draco-Flèches",
	"Thérémonie",
	"Octoprise",
	"Prise de Bec",
	"Branchicrok",
	"Change-Côté",
	"Dracacophonie",
	"Big Splash",
	"Nappage",
	"Tamb. Battant",
	"Troquenard",
	"BallonBrûlant",
	"GladusMaximus",
	"Aegis Maxima",
	"Roue Libre",
	"Abattage",
	"Tapotige",
	"Overdrive",
	"Acide Malique",
	"Force G",
	"Choc Émotion",
	"Vapeur Fée",
	"Fontaine Vie",
	"Blocage",
	"Fourbette",
	"Joute Astrale",
	"LaserInfinimx",
	"Métalaser",
	"Vaste Pouvoir",
	"Métalliroue",
	"RafalÉcailles",
	"Laser Météore",
	"Kokiyarme",
	"Explo-Brume",
	"Gliss'Herbe",
	"Monte-Tension",
	"Champlificat.",
	"RavageRampant",
	"Feu Envieux",
	"Cent Rancunes",
	"Esprit Frapp.",
	"Gaz Corrosif",
	"Coaching",
	"Eau Revoir",
	"Triple Axel",
	"Double Volée",
	"Sable Ardent",
	"Selve Salvat.",
	"Poing Obscur",
	"Torrent Coups",
	"Voltageôle",
	"Draco-Énergie",
	"RegardGlaçant",
	"FureurArdente",
	"CoupFulgurant",
	"Lance Glace",
	"ÉclatSpectral",
	"Sort Sinistre",
}
lang.fr.event_objects_names = {
	"brendan",
	"brendan on mach bike",
	"surfing brendan",
	"brendan",
	"quinty plump",
	"ninja boy",
	"twin",
	"light blue shirt boy",
	"red and yellow shirt girl",
	"blue and pink shirt boy",
	"blue and green dress girl",
	"little boy",
	"little girl",
	"magenta and grey shirt boy",
	"yellow and red shirt girl",
	"rich boy",
	"double ponytails woman",
	"fat man",
	"pokefan woman",
	"bald man",
	"ponytail woman",
	"expert old man",
	"expert old woman",
	"green coat man",
	"yellow and red woman",
	"pokefan man",
	"curly hair woman",
	"cook",
	"link receptionist",
	"old man",
	"old woman",
	"camper",
	"picnicker",
	"blond man",
	"red and white dress woman",
	"youngster",
	"bug catcher",
	"psychic man",
	"school kid boy",
	"maniac",
	"hex maniac",
	"rayquaza",
	"swimming man",
	"swimming woman",
	"black belt",
	"beauty",
	"light blue lab coat scientist",
	"lass",
	"gentleman",
	"sailor",
	"fisherman",
	"running triathlete man",
	"running triathlete woman",
	"tuber woman",
	"tuber man",
	"hiker",
	"cycling triathlete man",
	"cycling triathlete woman",
	"nurse",
	"item ball",
	"berry tree",
	"berry tree early stages",
	"berry tree late stages",
	"brendan acro bike",
	"prof birch",
	"magenta strip shirt man",
	"blond colored haire man",
	"reporter man",
	"reporter women",
	"bard",
	"anabel",
	"tucker",
	"greta",
	"spenser",
	"noland",
	"lucy",
	"unused natu doll",
	"unused magnemite doll",
	"unused squirtle doll",
	"unused wooper doll",
	"unused pikachu doll",
	"unused porygon2 doll",
	"cuttable tree",
	"mart employee",
	"rooftop sale woman",
	"teala",
	"breakable rock",
	"pushable boulder",
	"mr brineys boat",
	"may normal",
	"may mach bike",
	"may acro bike",
	"may surfing",
	"may field move",
	"truck",
	"vigoroth carrying box",
	"vigoroth facing away",
	"birchs bag",
	"zigzagoon first",
	"artist",
	"rival brendan normal",
	"rival brendan mach bike",
	"rival brendan acro bike",
	"rival brendan surfing",
	"rival brendan field move",
	"rival may normal",
	"rival may mach bike",
	"rival may acro bike",
	"rival may surfing",
	"rival may field move",
	"cameraman",
	"brendan underwater",
	"may underwater",
	"moving box",
	"cable car",
	"white lab coat scientist",
	"devon employee",
	"aqua member man",
	"aqua member woman",
	"magma member man",
	"magma member woman",
	"sidney",
	"phoebe",
	"glacia",
	"drake",
	"roxanne",
	"brawly",
	"wattson",
	"flannery",
	"norman",
	"winona",
	"liza",
	"tate",
	"wallace",
	"steven",
	"wally",
	"little boy with glasses",
	"brendan fishing",
	"may fishing",
	"hot springs old woman",
	"ss tidal",
	"submarine shadow",
	"pichu doll",
	"pikachu doll",
	"marill doll",
	"togepi doll",
	"cyndaquil doll",
	"chikorita doll",
	"totodile doll",
	"jigglypuff doll",
	"meowth doll",
	"clefairy doll",
	"ditto doll",
	"smoochum doll",
	"treecko doll",
	"torchic doll",
	"mudkip doll",
	"duskull doll",
	"wynaut doll",
	"baltoy doll",
	"kecleon doll",
	"azurill doll",
	"skitty doll",
	"swablu doll",
	"gulpin doll",
	"lotad doll",
	"seedot doll",
	"pika cushion",
	"round cushion",
	"kiss cushion",
	"zigzag cushion",
	"spin cushion",
	"diamond cushion",
	"ball cushion",
	"grass cushion",
	"fire cushion",
	"water cushion",
	"big snorlax doll",
	"big rhydon doll",
	"big lapras doll",
	"big venusaur doll",
	"big charizard doll",
	"big blastoise doll",
	"big wailmer doll",
	"big regirock doll",
	"big regice doll",
	"big registeel doll",
	"latias",
	"latios",
	"gameboy kid",
	"contest judge",
	"brendan watering",
	"may watering",
	"brendan decorating",
	"may decorating",
	"archie",
	"maxie",
	"kyogre front",
	"groudon front",
	"fossil",
	"regirock",
	"regice",
	"registeel",
	"skitty",
	"kecleon",
	"kyogre asleep",
	"groudon asleep",
	"rayquaza",
	"zigzagoon second",
	"pikachu",
	"azumarill",
	"wingull",
	"kecleon bridge shadow",
	"tuber man swimming",
	"azurill",
	"mom",
	"link brendan",
	"link may",
	"juan",
	"scott",
	"poochyena",
	"kyogre side",
	"groudon side",
	"mystery gift man",
	"trick house statue",
	"kirlia",
	"dusclops",
	"union room nurse",
	"sudowoodo",
	"mew",
	"red",
	"leaf",
	"deoxys",
	"deoxys triangle",
	"brandon",
	"link rs brendan",
	"link rs may",
	"lugia",
	"hooh",
}

lang.en = {}
lang.en = { 
	new_game = "New game",
	options = "Options",
	continue = "Continue",
	mystery_gift = "Mystery gift",
	mystery_events = "Mystery events",

	window = "window ",
	read_windows = "Read windows",
	credits = "credits",
	zone = "zone ",
	event = "event",
	north_event = "north event",
	south_event = "south event",
	east_event = "east event",
	west_event = "west event",
	hidden_event = "hidden event",
	secret_base_event = "secret base event",

	log_menu = "Log menu",
	poi_menu = "Points of interest menu",
	entity_mode = "Entity mode",
	passage_mode = "Passage mode",
	event_mode = "Event mode",
	connection_mode = "Connection mode",
	distance = " distance ",

	game_title = "Pokemon, emerald version, press start",
	change_time_ok = "Is this the right time ?",

	fight = "Fight",
	bag = "Bag",
	pokemon = "Pokemon",
	run = "Run",
	
	action_menu = "What must do ",
	move_menu = "Move menu",
	game_menu = "Game menu ...",
	gender_menu = "Gender menu ...",
	yes_no_menu = "Yes no menu ...",
	pause_menu = "Pause menu ...",
	game_keyboard = "Game keyboard menu", 
	shop_menu = "Shop menu ...",
	pc_menu = "PC menu ...",

	new_turn = new_turn_f,

	youareon = "You are on ",

	pokemon_choose = "choose a pokemon",
	leave = "Leave",
	change = "change ",
	_for = "for ",
	slot = "slot ",

	items_pocket = "Items pocket",
	balls_pocket = "Pokeballs pocket",
	thhm_pocket = "T,H & H,M pocket",
	berries_pocket = "Berries pocket",
	keyitems_pocket = "Key items pocket",
	
	--intro_callback = 135712429,
	--ingame_keyboard_callback = 135155545,

	upper_case = "upper case mode",
	lower_case = "lower case mode",
	other = "other characters mode",
	backspace = "backspace",
	
	entry = "entry ",
	targeted = " targeted",
	
	female = "female",
	male = "male",
	genderless = "",	
	
	selected = " selected",
	connection = "connection",
}

lang.en.connections = {
	SOUTH = "south connection",
	NORTH = "north connection",
	WEST = "west connection",
	EAST = "east connection",
	DIVE = "dive connection",
	EMERGE = "emerge connection",
}

lang.en.event_objects_names = {
	"brendan",
	"brendan on mach bike",
	"surfing brendan",
	"brendan",
	"quinty plump",
	"ninja boy",
	"twin",
	"light blue shirt boy",
	"red and yellow shirt girl",
	"blue and pink shirt boy",
	"blue and green dress girl",
	"little boy",
	"little girl",
	"magenta and grey shirt boy",
	"yellow and red shirt girl",
	"rich boy",
	"double ponytails woman",
	"fat man",
	"pokefan woman",
	"bald man",
	"ponytail woman",
	"expert old man",
	"expert old woman",
	"green coat man",
	"yellow and red woman",
	"pokefan man",
	"curly hair woman",
	"cook",
	"link receptionist",
	"old man",
	"old woman",
	"camper",
	"picnicker",
	"blond man",
	"red and white dress woman",
	"youngster",
	"bug catcher",
	"psychic man",
	"school kid boy",
	"maniac",
	"hex maniac",
	"rayquaza",
	"swimming man",
	"swimming woman",
	"black belt",
	"beauty",
	"light blue lab coat scientist",
	"lass",
	"gentleman",
	"sailor",
	"fisherman",
	"running triathlete man",
	"running triathlete woman",
	"tuber woman",
	"tuber man",
	"hiker",
	"cycling triathlete man",
	"cycling triathlete woman",
	"nurse",
	"item ball",
	"berry tree",
	"berry tree early stages",
	"berry tree late stages",
	"brendan acro bike",
	"prof birch",
	"magenta strip shirt man",
	"blond colored haire man",
	"reporter man",
	"reporter women",
	"bard",
	"anabel",
	"tucker",
	"greta",
	"spenser",
	"noland",
	"lucy",
	"unused natu doll",
	"unused magnemite doll",
	"unused squirtle doll",
	"unused wooper doll",
	"unused pikachu doll",
	"unused porygon2 doll",
	"cuttable tree",
	"mart employee",
	"rooftop sale woman",
	"teala",
	"breakable rock",
	"pushable boulder",
	"mr brineys boat",
	"may normal",
	"may mach bike",
	"may acro bike",
	"may surfing",
	"may field move",
	"truck",
	"vigoroth carrying box",
	"vigoroth facing away",
	"birchs bag",
	"zigzagoon first",
	"artist",
	"rival brendan normal",
	"rival brendan mach bike",
	"rival brendan acro bike",
	"rival brendan surfing",
	"rival brendan field move",
	"rival may normal",
	"rival may mach bike",
	"rival may acro bike",
	"rival may surfing",
	"rival may field move",
	"cameraman",
	"brendan underwater",
	"may underwater",
	"moving box",
	"cable car",
	"white lab coat scientist",
	"devon employee",
	"aqua member man",
	"aqua member woman",
	"magma member man",
	"magma member woman",
	"sidney",
	"phoebe",
	"glacia",
	"drake",
	"roxanne",
	"brawly",
	"wattson",
	"flannery",
	"norman",
	"winona",
	"liza",
	"tate",
	"wallace",
	"steven",
	"wally",
	"little boy with glasses",
	"brendan fishing",
	"may fishing",
	"hot springs old woman",
	"ss tidal",
	"submarine shadow",
	"pichu doll",
	"pikachu doll",
	"marill doll",
	"togepi doll",
	"cyndaquil doll",
	"chikorita doll",
	"totodile doll",
	"jigglypuff doll",
	"meowth doll",
	"clefairy doll",
	"ditto doll",
	"smoochum doll",
	"treecko doll",
	"torchic doll",
	"mudkip doll",
	"duskull doll",
	"wynaut doll",
	"baltoy doll",
	"kecleon doll",
	"azurill doll",
	"skitty doll",
	"swablu doll",
	"gulpin doll",
	"lotad doll",
	"seedot doll",
	"pika cushion",
	"round cushion",
	"kiss cushion",
	"zigzag cushion",
	"spin cushion",
	"diamond cushion",
	"ball cushion",
	"grass cushion",
	"fire cushion",
	"water cushion",
	"big snorlax doll",
	"big rhydon doll",
	"big lapras doll",
	"big venusaur doll",
	"big charizard doll",
	"big blastoise doll",
	"big wailmer doll",
	"big regirock doll",
	"big regice doll",
	"big registeel doll",
	"latias",
	"latios",
	"gameboy kid",
	"contest judge",
	"brendan watering",
	"may watering",
	"brendan decorating",
	"may decorating",
	"archie",
	"maxie",
	"kyogre front",
	"groudon front",
	"fossil",
	"regirock",
	"regice",
	"registeel",
	"skitty",
	"kecleon",
	"kyogre asleep",
	"groudon asleep",
	"rayquaza",
	"zigzagoon second",
	"pikachu",
	"azumarill",
	"wingull",
	"kecleon bridge shadow",
	"tuber man swimming",
	"azurill",
	"mom",
	"link brendan",
	"link may",
	"juan",
	"scott",
	"poochyena",
	"kyogre side",
	"groudon side",
	"mystery gift man",
	"trick house statue",
	"kirlia",
	"dusclops",
	"union room nurse",
	"sudowoodo",
	"mew",
	"red",
	"leaf",
	"deoxys",
	"deoxys triangle",
	"brandon",
	"link rs brendan",
	"link rs may",
	"lugia",
	"hooh",
}
lang.en.name = {
	"---", "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard",
	"Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree",
	"Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate",
	"Spearow", "Fearow", "Ekans", "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash",
	"Nidoran F", "Nidorina", "Nidoqueen", "Nidoran M", "Nidorino", "Nidoking",
	"Clefairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff",
	"Zubat", "Golbat", "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth",
	"Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck", "Mankey", "Primeape",
	"Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam",
	"Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel",
	"Geodude", "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro",
	"Magnemite", "Magneton", "Farfetch'd", "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer", "Muk",
	"Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix", "Drowzee", "Hypno",
	"Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak",
	"Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey",
	"Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu", "Starmie",
	"Mr. Mime", "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados",
	"Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar",
	"Kabuto", "Kabutops", "Aerodactyl", "Snorlax", "Articuno", "Zapdos", "Moltres",
	"Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew",

	"Chikorita", "Bayleef", "Meganium", "Cyndaquil", "Quilava", "Typhlosion",
	"Totodile", "Croconaw", "Feraligatr", "Sentret", "Furret", "Hoothoot", "Noctowl",
	"Ledyba", "Ledian", "Spinarak", "Ariados", "Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa",
	"Igglybuff", "Togepi", "Togetic", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Bellossom",
	"Marill", "Azumarill", "Sudowoodo", "Politoed", "Hoppip", "Skiploom", "Jumpluff", "Aipom",
	"Sunkern", "Sunflora", "Yanma", "Wooper", "Quagsire", "Espeon", "Umbreon", "Murkrow", "Slowking",
	"Misdreavus", "Unown", "Wobbuffet", "Girafarig", "Pineco", "Forretress", "Dunsparce", "Gligar",
	"Steelix", "Snubbull", "Granbull", "Qwilfish", "Scizor", "Shuckle", "Heracross", "Sneasel",
	"Teddiursa", "Ursaring", "Slugma", "Magcargo", "Swinub", "Piloswine", "Corsola", "Remoraid", "Octillery",
	"Delibird", "Mantine", "Skarmory", "Houndour", "Houndoom", "Kingdra", "Phanpy", "Donphan",
	"Porygon2", "Stantler", "Smeargle", "Tyrogue", "Hitmontop", "Smoochum", "Elekid", "Magby", "Miltank",
	"Blissey", "Raikou", "Entei", "Suicune", "Larvitar", "Pupitar", "Tyranitar", "Lugia", "Ho-Oh", "Celebi",
	
	"none","none","none","none","none",
	"none","none","none","none","none",
	"none","none","none","none","none",
	"none","none","none","none","none",
	"none","none","none","none","none",
	
	"Treecko", "Grovyle", "Sceptile",
	"Torchic", "Combusken", "Blaziken",
	"Mudkip", "Marshtomp", "Swampert",
	"Poochyena", "Mightyena", "Zigzagoon", "Linoone",
	"Wurmple", "Silcoon", "Beautifly", "Cascoon", "Dustox",
	"Lotad", "Lombre", "Ludicolo", "Seedot", "Nuzleaf", "Shiftry",		
	"Nincada", "Ninjask", "Shedinja", "Taillow", "Swellow",
	"Shroomish", "Breloom", "Spinda", "Wingull", "Pelipper",
	"Surskit", "Masquerain", "Wailmer", "Wailord", "Skitty", "Delcatty",
	"Kecleon", "Baltoy", "Claydol", "Nosepass", "Torkoal", "Sableye",
	"Barboach", "Whiscash", "Luvdisc", "Corphish", "Crawdaunt", "Feebas", "Milotic",	
	"Carvanha", "Sharpedo", "Trapinch", "Vibrava", "Flygon", "Makuhita", "Hariyama",
	"Electrike", "Manectric", "Numel", "Camerupt", "Spheal", "Sealeo", "Walrein", "Cacnea", "Cacturne",
	"Snorunt", "Glalie", "Lunatone", "Solrock", "Azurill", "Spoink", "Grumpig", "Plusle", "Minun",
	"Mawile", "Meditite", "Medicham", "Swablu", "Altaria", "Wynaut", "Duskull", "Dusclops", "Roselia",
	"Slakoth", "Vigoroth", "Slaking", "Gulpin", "Swalot", "Tropius", "Whismur", "Loudred", "Exploud",
	"Clamperl", "Huntail", "Gorebyss", "Absol", "Shuppet", "Banette", "Seviper", "Zangoose", "Relicanth",
	"Aron", "Lairon", "Aggron", "Castform", "Volbeat", "Illumise", "Lileep", "Cradily",
	"Anorith", "Armaldo", "Ralts", "Kirlia", "Gardevoir", "Bagon", "Shelgon", "Salamence", "Beldum",
	"Metang", "Metagross", "Regirock", "Regice", "Registeel", "Kyogre", "Groudon", "Rayquaza",
	"Latias", "Latios", "Jirachi", "Deoxys", "Chimecho",
	
	"Unown","Unown","Unown","Unown","Unown",
	"Unown","Unown","Unown","Unown","Unown",
	"Unown","Unown","Unown","Unown","Unown",
	"Unown","Unown","Unown","Unown","Unown",
	"Unown","Unown","Unown","Unown","Unown",
	"Unown","Unown"
}
lang.en.move = {
	"---",  "Pound", "Karate Chop", "DoubleSlap", "Comet Punch", "Mega Punch", "Pay Day",
	"Fire Punch", "Ice Punch", "ThunderPunch", "Scratch", "ViceGrip", "Guillotine",
	"Razor Wind", "Swords Dance", "Cut", "Gust", "Wing Attack", "Whirlwind", "Fly",
	"Bind", "Slam", "Vine Whip", "Stomp", "Double Kick", "Mega Kick", "Jump Kick",
	"Rolling Kick", "Sand-Attack", "Headbutt", "Horn Attack", "Fury Attack",
	"Horn Drill", "Tackle", "Body Slam", "Wrap", "Take Down", "Thrash", "Double-Edge",
	"Tail Whip", "Poison Sting", "Twineedle", "Pin Missile", "Leer", "Bite", "Growl",
	"Roar", "Sing", "Supersonic", "SonicBoom", "Disable", "Acid", "Ember",
	"Flamethrower", "Mist", "Water Gun", "Hydro Pump", "Surf", "Ice Beam", "Blizzard",
	"Psybeam", "BubbleBeam", "Aurora Beam", "Hyper Beam", "Peck", "Drill Peck",
	"Submission", "Low Kick", "Counter", "Seismic Toss", "Strength", "Absorb",
	"Mega Drain", "Leech Seed", "Growth", "Razor Leaf", "SolarBeam", "PoisonPowder",
	"Stun Spore", "Sleep Powder", "Petal Dance", "String Shot", "Dragon Rage",
	"Fire Spin", "ThunderShock", "Thunderbolt", "Thunder Wave", "Thunder", "Rock Throw",
	"Earthquake", "Fissure", "Dig", "Toxic", "Confusion", "Psychic", "Hypnosis",
	"Meditate", "Agility", "Quick Attack", "Rage", "Teleport", "Night Shade", "Mimic",
	"Screech", "Double Team", "Recover", "Harden", "Minimize", "SmokeScreen",
	"Confuse Ray", "Withdraw", "Defense Curl", "Barrier", "Light Screen", "Haze",
	"Reflect", "Focus Energy", "Bide", "Metronome", "Mirror Move", "Selfdestruct",
	"Egg Bomb", "Lick", "Smog", "Sludge", "Bone Club", "Fire Blast", "Waterfall",
	"Clamp", "Swift", "Skull Bash", "Spike Cannon", "Constrict", "Amnesia", "Kinesis",
	"Softboiled", "Hi Jump Kick", "Glare", "Dream Eater", "Poison Gas", "Barrage",
	"Leech Life", "Lovely Kiss", "Sky Attack", "Transform", "Bubble", "Dizzy Punch",
	"Spore", "Flash", "Psywave", "Splash", "Acid Armor", "Crabhammer", "Explosion",
	"Fury Swipes", "Bonemerang", "Rest", "Rock Slide", "Hyper Fang", "Sharpen", 
	"Conversion", "Tri Attack", "Super Fang", "Slash", "Substitute", "Struggle",
	"Sketch", "Triple Kick", "Thief", "Spider Web", "Mind Reader", "Nightmare",
	"Flame Wheel", "Snore", "Curse", "Flail", "Conversion 2", "Aeroblast",
	"Cotton Spore", "Reversal", "Spite", "Powder Snow", "Protect", "Mach Punch",
	"Scary Face", "Faint Attack", "Sweet Kiss", "Belly Drum", "Sludge Bomb",
	"Mud-Slap", "Octazooka", "Spikes", "Zap Cannon", "Foresight", "Destiny Bond",
	"Perish Song", "Icy Wind", "Detect", "Bone Rush", "Lock-On", "Outrage", "Sandstorm",
	"Giga Drain", "Endure", "Charm", "Rollout", "False Swipe", "Swagger", "Milk Drink",
	"Spark", "Fury Cutter", "Steel Wing", "Mean Look", "Attract", "Sleep Talk",
	"Heal Bell", "Return", "Present", "Frustration", "Safeguard", "Pain Split",
	"Sacred Fire", "Magnitude", "DynamicPunch", "Megahorn", "DragonBreath",
	"Baton Pass", "Encore", "Pursuit", "Rapid Spin", "Sweet Scent", "Iron Tail",
	"Metal Claw", "Vital Throw", "Morning Sun", "Synthesis", "Moonlight", "Hidden Power",
	"Cross Chop", "Twister", "Rain Dance", "Sunny Day", "Crunch", "Mirror Coat",
	"Psych Up", "ExtremeSpeed", "AncientPower", "Shadow Ball", "Future Sight",
	"Rock Smash", "Whirlpool", "Beat Up", "Fake Out", "Uproar", "Stockpile", "Spit Up",
	"Swallow", "Heat Wave", "Hail", "Torment", "Flatter", "Will-O-Wisp", "Memento",
	"Facade", "Focus Punch", "SmellingSalt", "Follow Me", "Nature Power", "Charge",
	"Taunt", "Helping Hand", "Trick", "Role Play", "Wish", "Assist", "Ingrain",
	"Superpower", "Magic Coat", "Recycle", "Revenge", "Brick Break", "Yawn", "Knock Off",
	"Endeavor", "Eruption", "Skill Swap", "Imprison", "Refresh", "Grudge", "Snatch",
	"Secret Power", "Dive", "Arm Thrust", "Camouflage", "Tail Glow", "Luster Purge",
	"Mist Ball", "FeatherDance", "Teeter Dance", "Blaze Kick", "Mud Sport", "Ice Ball",
	"Needle Arm", "Slack Off", "Hyper Voice", "Poison Fang", "Crush Claw", "Blast Burn",
	"Hydro Cannon", "Meteor Mash", "Astonish", "Weather Ball", "Aromatherapy",
	"Fake Tears", "Air Cutter", "Overheat", "Odor Sleuth", "Rock Tomb", "Silver Wind",
	"Metal Sound", "GrassWhistle", "Tickle", "Cosmic Power", "Water Spout",
	"Signal Beam", "Shadow Punch", "Extrasensory", "Sky Uppercut", "Sand Tomb",
	"Sheer Cold", "Muddy Water", "Bullet Seed", "Aerial Ace", "Icicle Spear",
	"Iron Defense", "Block", "Howl", "Dragon Claw", "Frenzy Plant", "Bulk Up",
	"Bounce", "Mud Shot", "Poison Tail", "Covet", "Volt Tackle", "Magical Leaf",
	"Water Sport", "Calm Mind", "Leaf Blade", "Dragon Dance", "Rock Blast",
	"Shock Wave", "Water Pulse", "Doom Desire", "Psycho Boost"

}
